### ISSUE TITLE
Defending Against Inference Attacks

### ISSUE THREAD

**Issue by miliable** [AISIGSJTU/Siren-Plus#2]
Hello, author. When I attempted to reproduce Figure 18, the contents of **mia_advantage.txt** and **mia_auc.txt** were empty. Could you please provide the experimental command needed to reproduce the experiment for Figure 18? I would greatly appreciate your response. Thank you very much!
![image](https://github.com/user-attachments/assets/9c067d05-e29a-4777-a8dc-ad146b286203)
![image](https://github.com/user-attachments/assets/c7f13026-a88e-4d0e-a97a-90fd86b3e2f7)
![image](https://github.com/user-attachments/assets/66172d8c-9cab-40f9-9e22-3ba646cff6bb)

**Comment by MarkGHX** [comment]
Thank you for your question. Could you please provide the command you used during the MIA experiments? Typically, you need to set both ```args.mal=True``` and ```args.mia=True``` to enable MIA in the code, as shown in line 301 in ```main.py```. If you only set ```args.mia=True```, the code will only output empty result files for MIA.

**Comment by miliable** [comment]
Thank you for your response. I had only used "--mia" previously, but following your method resolved the issue. My final command is: 
```
python main.py --dataset=fMNIST --k=10 --C=1.0 --E=5 --T=40 --B=64 --train --model_num=1 --gar=siren --mia --dp --dp_mul=1.0 --mal
```

**Comment by MarkGHX** [comment]
Thank you for the feedback! I'm glad the issue has been resolved. If you have any further questions, please feel free to reach out.
