### ISSUE TITLE
How to use the Census dataset for experiments

### ISSUE THREAD

**Issue by miliable** [AISIGSJTU/Siren-Plus#3]
Hello, author. Could you please explain how to use the Census dataset for experiments? Although I have downloaded the Census dataset and converted it to a `.mat` file, I am encountering many errors.

**Comment by MarkGHX** [comment]
Sorry for the inconvenience. The Census dataset is not officially supported or tested by us. The related code in the current repository was inherited from a previous codebase and has not been fully verified. As mentioned in our paper, we recommend using the MNIST, Fashion-MNIST, and CIFAR-10 datasets instead.

**Comment by miliable** [comment]
Thank you for your response. Could you please explain how to obtain the misclassification confidence values? Could you also provide the command for running the corresponding code?
![image](https://github.com/user-attachments/assets/1a13a00f-538f-4cd4-bb51-72c47ffeeefd)

**Comment by MarkGHX** [comment]
To obtain the misclassification confidence, you need to use targeted attacks. You could set ```--attack_type=targeted_model_poisoning```.

**Comment by miliable** [comment]
I previously set `--attack_type=targeted_model_poisoning`. Could you please tell me in which file the misclassification confidence values are stored?
![image](https://github.com/user-attachments/assets/298770ac-4d3b-4666-8449-d5eef8ccc869)

**Comment by MarkGHX** [comment]
The misclassification confidence results should be under ```./output_files``` instead of ```./output```.

**Comment by miliable** [comment]
Alright, thank you for your response.

**Comment by MarkGHX** [comment]
issue solved.
